[package]
name = "annoying_journal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fltk = "1.3.1"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
